"""The bootstrap flag — the one state in which an empty emission is honest.

## The problem this exists for

The vacuous-pass guard is structural, not a rule: `emission-1.0.schema.json`
sets `constants: minItems 1` and `counts.total/in_scope: minimum 1`, so an
emission of zero constants is not a representable artifact and every `mfc`
subcommand validates before it reads. That is the stronger arrangement and it
stays.

It also makes an adopter's first green build **unreachable**. A repository
generated by `mfc init` has no declarations yet, and the generated workflow
runs the emitter before anything has been written. Every new topic repo
therefore starts red, at the one moment the operator has the least evidence
about whether the tooling or their repository is at fault.

## The flag, and why it cannot be a general escape hatch

`formalization.yaml` carries `bootstrap: true`. While it is set:

* an emission with zero constants validates, against a copy of the schema with
  **exactly three** constraints dropped (`RELAXED`, below) and nothing else
  touched;
* every content rule reports `not_run`, never `pass` — the repository has
  nothing to check, and a green `mfc lint` over an empty emission would say
  the opposite;
* `mfc lint` **clears the flag itself** the first time it sees a non-empty
  emission, and records the date it did so.

The clearing is what keeps this from becoming a way to silence the guard. A
record that carries `bootstrap_cleared_at` may never carry `bootstrap: true`
again: `read()` raises on that combination rather than honouring it. The flag
is write-once and burns down, so "we set bootstrap while we sort out CI" is
not a state a repository can return to once it has had declarations.

## Why the record is edited textually

`formalization.yaml` is hand-written and comment-heavy — the comments are half
of what makes it a claim rather than decoration. Round-tripping it through
`yaml.safe_load` + `yaml.dump` would delete every one of them. `clear_text`
edits the single `bootstrap:` line and inserts one line after it, and raises
if that line is not there exactly once rather than guessing.
"""

from __future__ import annotations

import copy
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, NamedTuple

from .validate import load_artifact

#: Where the flag lives, relative to the topic repository root.
DEFAULT_RECORD = Path("formalization.yaml")

#: The three constraints — and only these three — that `bootstrap: true`
#: relaxes in `emission/1.0`. Stated as data so a test can assert that
#: relaxation touches nothing else.
RELAXED: tuple[tuple[str, ...], ...] = (
    ("properties", "constants", "minItems"),
    ("properties", "counts", "properties", "total", "minimum"),
    ("properties", "counts", "properties", "in_scope", "minimum"),
)

#: A top-level `bootstrap:` line with a boolean value, and an optional comment.
_FLAG_LINE = re.compile(
    r"^bootstrap:[ \t]*(?P<value>true|false)[ \t]*(?P<comment>#.*)?$", re.MULTILINE)


class RecordError(Exception):
    """`formalization.yaml` says something about the flag that cannot be honoured."""


class State(NamedTuple):
    """What the record says about bootstrapping, as read."""

    active: bool
    cleared_at: str | None
    path: Path

    @property
    def present(self) -> bool:
        """Whether a record was found at all. An absent record is not an error."""
        return self.path.is_file()


def read(path: Path | None = None) -> State:
    """Read the flag out of `formalization.yaml`.

    An absent record yields `active: False`. That is deliberate: the flag is an
    opt-in, and a repository with no record has not opted in. A record that is
    present but unreadable is an error, never a silent `False` — "I could not
    tell" and "it is off" are different facts.
    """
    path = Path(path) if path is not None else DEFAULT_RECORD
    if not path.is_file():
        return State(active=False, cleared_at=None, path=path)

    doc: Any = load_artifact(path)  # LoadError / CapabilityError propagate.
    if not isinstance(doc, dict):
        raise RecordError(f"{path.name}: not a mapping")

    active = doc.get("bootstrap", False)
    cleared_at = doc.get("bootstrap_cleared_at")
    if not isinstance(active, bool):
        raise RecordError(
            f"{path.name}: bootstrap must be true or false, not {active!r}")
    if cleared_at is not None and not isinstance(cleared_at, str):
        cleared_at = str(cleared_at)
    if active and cleared_at:
        raise RecordError(
            f"{path.name}: bootstrap: true, but the flag was already cleared on "
            f"{cleared_at}. It is write-once: a repository that has had "
            f"declarations may not re-enter the state where an empty emission "
            f"validates. Remove `bootstrap: true`.")
    return State(active=active, cleared_at=cleared_at, path=path)


def relax(schema: dict) -> dict:
    """A copy of `schema` with the vacuity constraints in `RELAXED` removed.

    The original is not mutated, and no other keyword is touched — an emission
    under bootstrap is still checked for every field, type, pattern and
    cross-field `allOf` the schema states. The only claim being suspended is
    "this repository has at least one declaration", which under bootstrap is
    the fact being reported rather than a defect.
    """
    out = copy.deepcopy(schema)
    for keys in RELAXED:
        node: Any = out
        for key in keys[:-1]:
            node = node.get(key) if isinstance(node, dict) else None
            if node is None:
                break
        if isinstance(node, dict):
            node.pop(keys[-1], None)
    return out


def is_empty(emission: dict) -> bool:
    """Whether this is an emission from a repository that has nothing in it yet.

    Deliberately narrower than "fails the vacuous-pass guard". The guard trips
    on two different situations and bootstrap may only excuse one of them:

    * `constants: []` with `counts.total == 0` — a repository with no
      declarations. Every new topic repo starts here, and it is the state this
      flag exists for.
    * constants present, `counts.in_scope == 0` — a **mis-scoped emitter**,
      which swept something and matched none of it against the root library.
      That is a defect at any point in a repository's life, and the
      `empty-emission` fixture is exactly this case. Bootstrap does not touch
      it: a fresh repo whose emitter is pointed at the wrong root still fails,
      which is the whole reason the guard exists.
    """
    counts = emission.get("counts") or {}
    return (not emission.get("constants")
            and counts.get("total") == 0
            and counts.get("in_scope") == 0)


def has_declarations(emission: dict) -> bool:
    """Whether this emission is evidence that the repository has started.

    The condition for CLEARING the flag, and deliberately not the negation of
    `is_empty`. Three states, not two:

    * empty (`is_empty`) — bootstrap applies;
    * in-scope declarations present — bootstrap is over, and clearing is
      recorded;
    * neither, i.e. a mis-scoped or otherwise broken emission — the flag is
      left exactly as it was. Burning a write-once flag on the strength of a
      defective artifact would mean a repository could lose its bootstrap
      state to a bad emitter run and never get it back.
    """
    counts = emission.get("counts") or {}
    return bool(emission.get("constants")) and (counts.get("in_scope") or 0) >= 1


def today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def clear_text(text: str, at: str) -> str:
    """Turn `bootstrap: true` into `bootstrap: false` plus a dated clearing.

    Pure, so the edit is testable without a filesystem. Raises if the line is
    absent or appears more than once rather than editing the wrong one.
    """
    matches = list(_FLAG_LINE.finditer(text))
    if len(matches) != 1:
        raise RecordError(
            f"expected exactly one top-level `bootstrap:` line, found {len(matches)}")
    match = matches[0]
    if match.group("value") != "true":
        raise RecordError("`bootstrap:` is not true; nothing to clear")
    comment = f"  {match.group('comment')}" if match.group("comment") else ""
    replacement = (
        f"bootstrap: false{comment}\n"
        f"bootstrap_cleared_at: {at}   # write-once; bootstrap may never be re-set")
    return text[:match.start()] + replacement + text[match.end():]


def clear(path: Path, at: str | None = None) -> str:
    """Clear the flag in the record at `path`. Returns the date recorded."""
    at = at or today()
    path = Path(path)
    path.write_text(clear_text(path.read_text(encoding="utf-8"), at), encoding="utf-8")
    return at
