"""Tests for the volatile-property lint and the run/1.0 split — #160.

`git diff --exit-code attest/` is one of four claimed sorry-gates and the only
one that survives the seam. Two separate things were wrong with it:

1. **It could never pass.** `bundle.json` carried `produced_at` per predicate
   and `build.json` carried `produced_at` plus `ci{run_url, workflow_sha,
   runner}`. Both are committed and both changed every run, so the gate went
   red on no-op commits.
2. **It could never fail.** The generated `.gitignore` ignored `/attest/*.json`
   wholesale, so the diff compared nothing at all. A gate that cannot fail is
   not a weaker gate, it is a green step.

Fixing (1) without (2) would have produced a gate that passes for the wrong
reason, which is indistinguishable from the bug. Both are tested here.
"""

from __future__ import annotations

import json
from pathlib import Path

from contract.mfc.lint import (
    CI_REGENERATED_ARTIFACTS,
    VOLATILE_PROPERTY_NAMES,
    artifact_name,
    lint_volatile,
)
from contract.mfc.cli import EXIT_FINDINGS, EXIT_OK, main
from contract.mfc.scaffold import GITIGNORE, WORKFLOW
from contract.mfc.validate import SCHEMA_DIR

HERE = Path(__file__).resolve().parent
VALID_DIR = HERE.parent / "testdata" / "artifacts" / "valid"
INVALID_SCHEMAS = HERE.parent / "testdata" / "schemas" / "invalid"


# --------------------------------------------------------------------------
# The lint fires, and fires only where it should.
# --------------------------------------------------------------------------

def test_the_rejection_fixture_is_rejected() -> None:
    """A gate with no failing case is not evidence."""
    doc = json.loads((INVALID_SCHEMAS / "bundle-9.9.schema.json").read_text())
    findings = lint_volatile(doc, "bundle-9.9.schema.json")
    assert {f.name for f in findings} == {"produced_at", "run_url"}, \
        "the walk must reach $defs, not just top-level properties"


def test_the_shipped_schemas_are_clean() -> None:
    assert main(["lint-schemas", "--schema-dir", str(SCHEMA_DIR)]) == EXIT_OK


def test_lint_schemas_fails_on_the_rejection_fixtures() -> None:
    assert main(["lint-schemas", "--schema-dir", str(INVALID_SCHEMAS)]) == EXIT_FINDINGS


def test_an_uncommitted_artifact_may_carry_a_timestamp() -> None:
    """`emission` is regenerated every run and is NOT committed."""
    doc = json.loads((SCHEMA_DIR / "emission-1.0.schema.json").read_text())
    assert "emitted_at" in doc["properties"], "the premise of this test"
    assert lint_volatile(doc, "emission-1.0.schema.json") == []


def test_a_human_act_may_carry_its_own_date() -> None:
    """`reviewed_at` and `generated_at` are content, not run metadata.

    Both artifacts are committed, and neither is regenerated by CI on every
    commit — they are written by a deliberate human or offline act. The date a
    person reviewed a statement IS the fact being recorded, and banning it
    would delete evidence to protect a gate it does not threaten.
    """
    for name in ("review-1.0.schema.json", "resolution-1.0.schema.json"):
        doc = json.loads((SCHEMA_DIR / name).read_text())
        assert lint_volatile(doc, name) == []


def test_artifact_name_reads_the_filename() -> None:
    assert artifact_name("bundle-1.0.schema.json") == "bundle"
    assert artifact_name("aggregate-status.schema.json") == "aggregate"
    assert artifact_name("nonsense.json") == ""


def test_run_is_not_itself_policed() -> None:
    """run/1.0 is where the volatile fields were moved TO."""
    assert "run" not in CI_REGENERATED_ARTIFACTS
    doc = json.loads((SCHEMA_DIR / "run-1.0.schema.json").read_text())
    assert lint_volatile(doc, "run-1.0.schema.json") == []


# --------------------------------------------------------------------------
# The split itself.
# --------------------------------------------------------------------------

def test_the_committed_schemas_no_longer_declare_what_moved() -> None:
    build = json.loads((SCHEMA_DIR / "build-1.0.schema.json").read_text())
    assert "produced_at" not in build["properties"]
    assert "ci" not in build["properties"]
    assert "ci" not in build["required"] and "produced_at" not in build["required"]

    bundle = json.loads((SCHEMA_DIR / "bundle-1.0.schema.json").read_text())
    predicate = bundle["$defs"]["predicate"]
    assert "produced_at" not in predicate["properties"]
    assert "produced_at" not in predicate["required"]


def test_run_1_0_carries_everything_that_moved() -> None:
    run = json.loads((SCHEMA_DIR / "run-1.0.schema.json").read_text())
    assert "produced_at" in run["properties"]
    assert set(run["properties"]["ci"]["properties"]) == {
        "run_url", "workflow_sha", "runner"}


def test_run_1_0_joins_back_to_the_committed_tree() -> None:
    """A release asset nobody can tie to a commit is not provenance."""
    run = json.loads((SCHEMA_DIR / "run-1.0.schema.json").read_text())
    files = run["properties"]["files"]
    assert files["minItems"] == 1, "a run that names no output is not a record of one"
    assert set(files["items"]["required"]) == {"file", "sha256"}


def test_the_contract_pin_stays_in_the_bundle() -> None:
    """`contract_repo.rev` is a PIN. A pin that changed per run is not pinning."""
    bundle = json.loads((SCHEMA_DIR / "bundle-1.0.schema.json").read_text())
    assert "contract_repo" in bundle["required"]


def test_every_valid_instance_still_validates() -> None:
    for path in sorted(VALID_DIR.glob("*.json")):
        assert main(["validate", str(path)]) == EXIT_OK, path.name


# --------------------------------------------------------------------------
# The other half: the gate must be able to FAIL.
# --------------------------------------------------------------------------

def _rules(text: str) -> set[str]:
    """The lines git acts on. Comments explain the rule; they are not the rule."""
    return {line.strip() for line in text.splitlines()
            if line.strip() and not line.lstrip().startswith("#")}


def test_the_generated_gitignore_does_not_ignore_what_the_gate_compares() -> None:
    rules = _rules(GITIGNORE)
    assert "/attest/*.json" not in rules, \
        "ignoring attest/*.json makes `git diff --exit-code attest/` compare nothing"
    assert {"/attest/run.json", "/attest/lean-emission.json"} <= rules


def test_git_itself_agrees(tmp_path: Path) -> None:
    """Asserted against real git, not against the text of the file.

    A rule can be present and still not do what it reads like — `/attest/`
    versus `/attest/*.json` versus a negation ordering — and this gate is only
    worth having if git's answer is the one being checked.
    """
    import subprocess

    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    (tmp_path / ".gitignore").write_text(GITIGNORE, encoding="utf-8")
    (tmp_path / "attest").mkdir()

    def ignored(rel: str) -> bool:
        return subprocess.run(["git", "check-ignore", "-q", rel],
                              cwd=tmp_path).returncode == 0

    assert ignored("attest/run.json"), "run/1.0 is provenance, not evidence"
    assert ignored("attest/lean-emission.json"), "the emitter's raw output is an input"
    for committed in ("attest/declarations.json", "attest/environment.json",
                      "attest/bundle.json", "attest/build.json"):
        assert not ignored(committed), \
            f"{committed} is what the gate compares; ignoring it makes the gate vacuous"


def test_the_generated_workflow_still_has_the_gate() -> None:
    assert "git diff --exit-code" in WORKFLOW
    assert "attest/" in WORKFLOW


def test_no_committed_generated_artifact_is_left_ignored(tmp_path: Path) -> None:
    """Every artifact the workflow writes is either ignored on purpose or diffed.

    The failure this guards against is a new artifact being added to the
    workflow and silently landing in neither category.
    """
    written = {"attest/lean-emission.json", "attest/environment.json",
               "attest/declarations.json"}
    ignored = {line.lstrip("/") for line in GITIGNORE.splitlines()
               if line.startswith("/attest/")}
    for artifact in written:
        assert artifact in ignored or "attest/" in WORKFLOW, artifact
    assert "attest/environment.json" not in ignored, \
        "environment.json is committed evidence and must be diffed"
